### ISSUE TITLE
Problem with Twitch VOD ?

### ISSUE THREAD

**Issue by MonkeyDMax92** [23rd/PotPlayerExtentions#11] opened 2019-08-26 22:09 UTC
Hi, I have a problem with VOD Twitch for some time: when I want to watch a VOD, it puts the message " **_"DXVA"_** video decoder is required to play the file ' and I only have the audio of the VOD without the image (see Attachment). I install the codec as requested but I do not know how to configure it.
Thanks for the help

PS:
- I do not know when the problem occurred, it's been that I have not watched VOD, I did not change anything in the 'Video' settings yet.  
- Twitch VOD/Live do not work on vlc

![Annotation 2019-08-26 235404](https://user-images.githubusercontent.com/42703828/63726241-fd13f200-c85c-11e9-9579-3fd37010ed1e.png)

**Comment by 23rd** [comment] 2019-08-27 09:27
Hello.
Can you share a sample link of any Twitch VOD?

>Twitch VOD/Live do not work on vlc

Do you mean VLC with Streamlink?
Perhaps something wrong with OS.

**Comment by MonkeyDMax92** [comment] 2019-08-27 12:00
Potplayer : 
For example, this link does not work: [https://www.twitch.tv/videos/472237232](url) ("DXVA" problem) unlike this one where it works perfectly:  [https://www.twitch.tv/videos/470394199](url) 🤷‍♂️
VLC:
- With Streamlink: VODs work but it's impossible to choose the timecode of the video.
- Without Streamlink: VODs do not work at all but sound sometimes and crash VLC (can not close the application)

**Comment by 23rd** [comment] 2019-09-02 16:09
Unfortunately, I still think the problem is in your operating system. It would be nice if you could check the extension in the virtual machine.

**Comment by MonkeyDMax92** [comment] 2019-09-04 00:58
My operating system ? Windows 10 Familly  Ver.1903 (18362.295) (64 bits)  | AMD A4-5150M APU with Radeon™ HD Graphics 2.70GHz / 8Go RAM (/HP Pavillon 17 Notebook PC) 

> It would be nice if you could check the extension in the virtual machine.

How can I do ?

**Comment by MonkeyDMax92** [comment] 2019-09-11 16:37
Since I woke up,  YouTube and Twitch VODs (all videos) on PotPlayer does not work, I'm the only one ? 🤔

**Comment by MonkeyDMax92** [comment] 2019-09-19 19:40
I restart because I still have the same problem before and for a few days **Twitch Your Follow** does not work completely despite my attempts. (see Screenshot)

![image](https://user-images.githubusercontent.com/42703828/65275060-17bc4c80-db25-11e9-8b11-68f434289159.png)

**Comment by 23rd** [comment] 2019-09-27 22:32
I updated the API for extensions and now the related to streams/vods/clips information should be displayed correctly.

**Comment by 23rd** [comment] 2019-09-27 22:40
> For example, this link does not work: https://www.twitch.tv/videos/472237232 ("DXVA" problem) unlike this one where it works perfectly: https://www.twitch.tv/videos/470394199 🤷‍♂️

Okay, I can confirm the problem.
The first link shows me the "DXVA" error.

But unfortunately, it's not a problem with my extension, it's a problem with the Potplayer itself.
These are direct links to the corresponding vods with 480p quality.
[https://twitch.tv/videos/472237232](twitch.tv/videos/472237232) — https://vod-metro.twitch.tv/a05f2a7ddffd0ec83a68_at0mium_35427870480_1282916671/480p30/index-muted-VMDMS97115.m3u8

[https://twitch.tv/videos/470394199](twitch.tv/videos/470394199) — https://vod-metro.twitch.tv/97a9b60b11fbce3782dc_bryandechart_35380455392_1279952821/480p30/index-dvr.m3u8

You can copy these links and paste them into any videoplayer, such as VLC, MPV, Potplayer etc.
You're still gonna have this problem in Potplayer even with the direct link.
So "DXVA" error has no relation to my extension and I have to close this issue.

**Closed by 23rd** 2019-09-27 22:40 UTC

**Comment by MonkeyDMax92** [comment] 2019-09-27 22:53
Thanks 🙏

**Comment by 23rd** [comment] 2019-09-27 22:54
You're welcome. =)

**Comment by U1s2e3r4n5a6m7e** [comment] 2019-10-30 22:38
That was the solution for me when I get DXVA error on some video files:
https://github.com/Nevcairiel/LAVFilters/releases
(install_video.bat)

@MonkeyDMax92

**Comment by MonkeyDMax92** [comment] 2019-10-30 23:22
I just have to install the * .bat?

**Comment by U1s2e3r4n5a6m7e** [comment] 2019-10-31 00:18
> 
> 
> I just have to install the install_video.bat ?

Yes. I hope this will fix the problem like mine.

**Comment by MonkeyDMax92** [comment] 2019-10-31 00:20
Thanks 🙏

**Comment by MonkeyDMax92** [comment] 2020-12-03 03:37
URL List is broken again (Twitch /YT) 😭
